/*
 * This source file was generated by the Gradle 'init' task
 */
package org.workPall;

import org.workPall.GUI.MainGUI;

import java.sql.SQLException;

public class Main {
    public static void main(String[] args) throws SQLException {
        MainGUI mainGui = new MainGUI();
        mainGui.displayAuth();
    }
}
